# Generated by Django 2.0 on 2018-07-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='eth_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
