# Generated by Django 2.0 on 2018-07-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamowner',
            name='last_bid',
            field=models.FloatField(default=0),
        ),
    ]
