# Generated by Django 2.0 on 2018-07-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180723_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='transactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='transactions',
            field=models.IntegerField(default=0),
        ),
    ]
