# Generated by Django 2.0 on 2018-07-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180721_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='owner',
            field=models.CharField(default='Unassigned', max_length=50),
        ),
    ]
